FROM python:3.14.7
WORKDIR /app
COPY /src /app/src
RUN pip install -r src/controller/dependences/requirements.txt
CMD ["python", "-m", "src.service.db.migration", "make_migration_tables", "&&", "python", "-m", "src.service.admin", "create_admin"]
