FROM python:3.14.7

WORKDIR /app
COPY /src /app/src/
RUN pip install -r src/controller/dependences/requirements.txt
CMD ["python", "-m", "uvicorn", "src.aplication.main:app","--host", "0.0.0.0","--port", "8000", "--reload"]

