FROM python:3.14.7

WORKDIR /app
COPY /src /app/src/
RUN pip install -r src/controller/dependences/requirements.txt
CMD ["python", "-m", "celery", "-A", "src.service.task:task_app","worker", "--loglevel=INFO"]