name: unit

on: 
    push:
        branches:
            - main
            - develop
            - future/database
            - future/sender
            - task/celery

    pull_request:
        branches:
            - main
            - develop



jobs:

    ambient:

        runs-on: ubuntu-latest
        environment: develop

        env:

                redis_port: ${{ secrets.REDIS_PORT }}
                redis_host: ${{ secrets.REDIS_HOST }}
                url: ${{ secrets.URL }}
                sing: ${{ secrets.SING }}
                origin: ${{ secrets.ORIGIN }}
                rate_limit: ${{ secrets.RATE_LIMIT }}
                global_rate_limit: ${{ secrets.GLOBAL_RATE_LIMIT }}
                email_user: ${{ secrets.EMAIL_USER }}
                password_user: ${{ secrets.PASSWORD_USER }}
                open_ai_key: ${{ secrets.OPEN_AI_KEY}}
        services:
          redis:
            image: redis:alpine
            ports:
              - 6379:6379
              

        steps:

            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: "3.14"

            - name: logs tests

              run: python -m tests.unit.logs
        
            
            - name: config test

              
              run: |
               pip install python-dotenv
               python -m tests.unit.config
    
            - name: sender email
              run: |
               pip install yagmail
               python -m tests.unit.sender

            - name: tasks
              run: |
               pip install celery redis
               python -m celery -A tests.unit.tasks:app_task worker --loglevel=INFO --detach
               python -m tests.unit.tasks
               python -m celery -A tests.unit.tasks:app_task inspect ping

              




          

          