name: unit

on: 
    push:
        branches:
            - main
            - develop
            - future/database
            - future/sender

    pull_request:
        branches:
            - main
            - develop



jobs:

    ambient:

        runs-on: ubuntu-latest
        environment: develop

        steps:

            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: "3.14"

            - name: logs tests

              run: python -m tests.unit.logs
        
            
            - name: config test
              env:

                redis_port: ${{ secrets.REDIS_PORT }}
                redis_host: ${{ secrets.REDIS_HOST }}
                url: ${{ secrets.URL }}
                sing: ${{ secrets.SING }}
                origin: ${{ secrets.ORIGIN }}
                rate_limit: ${{ secrets.RATE_LIMIT }}
                global_rate_limit: ${{ secrets.GLOBAL_RATE_LIMIT }}
                email_user: ${{ secrets.EMAIL_USER }}
                password_user: ${{ secrets.PASSWORD_USER }}
              
              run: |
               pip install python-dotenv
               python -m tests.unit.config
               python -m tests.unit.sender

          